In [3]:
import pandas as pd

list_example = [5,10,15,20,25]

list_example


[5, 10, 15, 20, 25]

In [4]:
pd.DataFrame(data= list_example , columns= ["values"], dtype= float)

values
0     5.0
1    10.0
2    15.0
3    20.0
4    25.0

In [6]:
import numpy as np
import pandas as pd

arr = np.random.randint(0,50 ,(4,4))

arr

array([[42, 49, 28,  1],
       [30, 29, 11,  4],
       [43, 18, 43, 38],
       [ 0, 39, 39, 21]])

In [7]:
df = pd.DataFrame(arr, index= ["a","b","c","d"], columns = ["val1", "val2","val3","val4"])

df

val1  val2  val3  val4
a    42    49    28     1
b    30    29    11     4
c    43    18    43    38
d     0    39    39    21

In [9]:
#--------------Dataframe with dictionary-----------

import numpy as np
import pandas as pd

p = np.random.randint(10,50 ,size=6)
p

array([40, 31, 43, 12, 19, 38])

In [10]:
u = np.random.randint(10,50 ,size=6)
s = np.random.randint(10,50 ,size=6)
h = np.random.randint(10,50 ,size=6)

dict_exam = {"val1" : p , "val2" : u ,"val3" :s ,"val4" :h}

dict_exam


{'val1': array([40, 31, 43, 12, 19, 38]),
 'val2': array([41, 24, 22, 29, 44, 18]),
 'val3': array([23, 49, 23, 26, 49, 17]),
 'val4': array([28, 32, 11, 42, 32, 30])}

In [13]:
df = pd.DataFrame(dict_exam)

df

val1  val2  val3  val4
0    40    41    23    28
1    31    24    49    32
2    43    22    23    11
3    12    29    26    42
4    19    44    49    32
5    38    18    17    30

In [14]:
df.head() # by default 5 value

val1  val2  val3  val4
0    40    41    23    28
1    31    24    49    32
2    43    22    23    11
3    12    29    26    42
4    19    44    49    32

In [15]:
df.head(3)

val1  val2  val3  val4
0    40    41    23    28
1    31    24    49    32
2    43    22    23    11

In [16]:
df.tail(3)

val1  val2  val3  val4
3    12    29    26    42
4    19    44    49    32
5    38    18    17    30

In [17]:
df.columns

Index(['val1', 'val2', 'val3', 'val4'], dtype='object')

In [20]:
[i for i in df.columns]

['val1', 'val2', 'val3', 'val4']

In [21]:
 df

val1  val2  val3  val4
0    40    41    23    28
1    31    24    49    32
2    43    22    23    11
3    12    29    26    42
4    19    44    49    32
5    38    18    17    30

In [22]:
df.columns =["new1" , "new2" ,"new3" ,"new4"]

df

new1  new2  new3  new4
0    40    41    23    28
1    31    24    49    32
2    43    22    23    11
3    12    29    26    42
4    19    44    49    32
5    38    18    17    30

In [23]:
df.values

array([[40, 41, 23, 28],
       [31, 24, 49, 32],
       [43, 22, 23, 11],
       [12, 29, 26, 42],
       [19, 44, 49, 32],
       [38, 18, 17, 30]])

In [24]:
type(df.values)

numpy.ndarray

In [25]:
type(df)

pandas.core.frame.DataFrame

In [26]:
df.shape

(6, 4)

In [27]:
df.ndim

2

In [28]:
df.size

24