In [1]:
# reshape fn is used to shape the numpy array
import numpy as np

example = np.arange(1,16)

example




array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [2]:
example.reshape((3,5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [3]:
array = example.reshape((1,15))

array

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [4]:
example.ndim

1

In [5]:
array.ndim

2

In [6]:
example.reshape((4,3))

ValueError: cannot reshape array of size 15 into shape (4,3)

In [7]:
#max()--returns largest element  argmax()--->returns index number of the largest element

import numpy as np

array = np.random.randint(0,15,10)

array


array([ 5,  3, 12, 10, 11,  9, 13,  1,  2,  5])

In [8]:
array.max()

13

In [9]:
array.argmax()

6

In [10]:
array2 = np.random.randint(0,50,(4,3))

array2

array([[48, 28, 48],
       [27,  3, 46],
       [ 5, 24, 42],
       [34,  2, 26]])

In [11]:
array2.max()

48

In [12]:
array2.argmax()

0

In [13]:
import numpy as np #min() argmax()
 
array = np.random.randint(20,70,10)

array


array([66, 23, 38, 58, 48, 55, 33, 51, 68, 27])

In [14]:
array.min()

23

In [15]:
array.argmin()

1

In [16]:
array2 = np.random.randint(20,70,(5,3))

array2

array([[55, 25, 67],
       [43, 52, 60],
       [62, 28, 34],
       [40, 47, 26],
       [46, 25, 43]])

In [17]:
array2.min()

25

In [18]:
array2.argmin()

1

In [19]:
import numpy as np 

arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

np.concatenate([arr1,arr2])


array([1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
arr3 = np.arange(1,7).reshape((2,3))

arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
arr4 = np.array([[7,8,9],[10,11,12]])

arr4

array([[ 7,  8,  9],
       [10, 11, 12]])

In [22]:
np.concatenate([arr3,arr4])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [23]:
np.concatenate([arr3,arr4],axis = 1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [24]:
np.concatenate([arr1,arr3])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [4]:
import numpy as np
arr5 = np.arange(1,11).reshape(5,2)

arr5

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [26]:
import numpy as np 

array = np.array([1,3,5,50,2,4,6])

np.split(array,[4,5])


[array([ 1,  3,  5, 50]), array([2]), array([4, 6])]

In [27]:
x,y,z = np.split(array,[4,5])

x

array([ 1,  3,  5, 50])

In [28]:
y

array([2])

In [29]:
z

array([4, 6])

In [34]:
import numpy as np 

array = np.array([1,3,5,50,2,4,6,8])

np.split(array,4)

[array([1, 3]), array([ 5, 50]), array([2, 4]), array([6, 8])]

In [35]:
np.split(array,5)

ValueError: array split does not result in an equal division

In [36]:
import numpy as np 

arr = np.arange(20).reshape(5,4)

arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [37]:
np.split(arr,[1,3])

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [38]:
x,y,z = np.split(arr,[1,3])

In [39]:
x

array([[0, 1, 2, 3]])

In [40]:
y

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
z

array([[12, 13, 14, 15],
       [16, 17, 18, 19]])

In [46]:
np.split(arr,[1,3], axis = 1)

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [47]:
#hsplit function

arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [48]:
np.hsplit(arr,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13],
        [17]]),
 array([[ 2],
        [ 6],
        [10],
        [14],
        [18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [49]:
np.hsplit(arr,[1,3])

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [50]:
#vsplit no axis parameter

arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [51]:
np.vsplit(arr,5)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]

In [52]:
np.vsplit(arr,[2,4])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]

In [53]:
#sort
import numpy as np

var = np.array([3,5,1,8,6,2,9])

var

array([3, 5, 1, 8, 6, 2, 9])

In [54]:
np.sort(var)

array([1, 2, 3, 5, 6, 8, 9])

In [55]:
var2 = np.sort(var)

var2

array([1, 2, 3, 5, 6, 8, 9])

In [56]:
example = np.random.normal(30,10,(4,4))
example

array([[25.15433144, 22.49524575, 22.55339753, 33.27225242],
       [35.45885069, 24.74565398, 41.73941576, 29.5896067 ],
       [21.71787921, 25.74747615, 30.25035916, 34.19653357],
       [37.24960765, 31.19326658, 45.61553794, 17.25162737]])

In [57]:
np.sort(example,axis=0)

array([[21.71787921, 22.49524575, 22.55339753, 17.25162737],
       [25.15433144, 24.74565398, 30.25035916, 29.5896067 ],
       [35.45885069, 25.74747615, 41.73941576, 33.27225242],
       [37.24960765, 31.19326658, 45.61553794, 34.19653357]])

In [58]:
np.sort(example,axis=1)

array([[22.49524575, 22.55339753, 25.15433144, 33.27225242],
       [24.74565398, 29.5896067 , 35.45885069, 41.73941576],
       [21.71787921, 25.74747615, 30.25035916, 34.19653357],
       [17.25162737, 31.19326658, 37.24960765, 45.61553794]])