In [2]:
#INDEXING

import numpy as np

array = np.arange(0,11)

array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
array[4]

4

In [4]:
array[-2]

9

In [5]:
var = np.array([[5,10,15],[20,25,30],[35,40,45]])

var

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [6]:
var[0,0]

5

In [7]:
var[2,1]

40

In [8]:
var[-1,-3]

35

In [9]:
#SLICING start ,stop,step

import numpy as np

exam = np.arange(10,20)

exam

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [10]:
exam[2:6]

array([12, 13, 14, 15])

In [11]:
exam[3::2]

array([13, 15, 17, 19])

In [12]:
exam[:7:3]

array([10, 13, 16])

In [14]:
#2d alicing

import numpy as np

vec = np.arange(30).reshape(6,5)

vec

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [15]:
vec[2,:]

array([10, 11, 12, 13, 14])

In [16]:
vec[2
    ]

array([10, 11, 12, 13, 14])

In [17]:
vec[0]

array([0, 1, 2, 3, 4])

In [18]:
vec[:,2]

array([ 2,  7, 12, 17, 22, 27])

In [19]:
vec[:,0]

array([ 0,  5, 10, 15, 20, 25])

In [20]:
vec[1:4,0:3]

array([[ 5,  6,  7],
       [10, 11, 12],
       [15, 16, 17]])

In [21]:
vec[0::2, 0::2]

array([[ 0,  2,  4],
       [10, 12, 14],
       [20, 22, 24]])

In [23]:
import numpy as np

push = np.array([0,1,2,3,4,5,6,9,8,9])

push

array([0, 1, 2, 3, 4, 5, 6, 9, 8, 9])

In [25]:
push[4] = 4

push[7] =7

push

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
push[0:5] = 10

push

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9])

array([5, 6, 7, 8, 9])

In [29]:
push[0:5] = 20,30,40,50,60

In [30]:
push

array([20, 30, 40, 50, 60,  5,  6,  7,  8,  9])

In [31]:
import numpy as np

mat = np.array([[10,20,30],
               [40,50,60],
               [70,80,90]])

mat[1, 1] = 100

mat

                            

array([[ 10,  20,  30],
       [ 40, 100,  60],
       [ 70,  80,  90]])

In [33]:
mat[1,0] =100.6
mat

array([[ 10,  20,  30],
       [100, 100,  60],
       [ 70,  80,  90]])

In [34]:
mat[:,2] = 100
mat

array([[ 10,  20, 100],
       [100, 100, 100],
       [ 70,  80, 100]])

In [36]:
mat[0::2,0:2]
mat

array([[ 10,  20, 100],
       [100, 100, 100],
       [ 70,  80, 100]])

In [37]:
mat[0::2,0:2] =100
mat

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [38]:
mat[0]

array([100, 100, 100])

In [39]:
mat[0] = 10,20,30
mat

array([[ 10,  20,  30],
       [100, 100, 100],
       [100, 100, 100]])

In [1]:
import numpy as np

fancy  = np.arange(0,50,5)

fancy


array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [2]:
fancy[5]

25

In [3]:
[fancy[1],fancy[3],fancy[5]]

[5, 15, 25]

In [4]:
indexes = [1,3,5]

fancy[indexes]


array([ 5, 15, 25])

In [5]:
array = np.array([1,3,5])

fancy[array]

array([ 5, 15, 25])

In [8]:
import numpy as np

var = np.zeros((10,10), dtype= "int")

var

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [9]:
var.shape

(10, 10)

In [10]:
var.shape[0]

10

In [12]:
row = var.shape[0]

In [13]:
 for i in range(row):
     var[i] = i
 

In [14]:
var

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [18]:
list1 = [1,3,5,7]

var[list1]

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7]])

In [19]:
list2 = [8,5,2,7,3 ]

var[list2]

array([[8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [20]:
example = np.arange(1,17).reshape((4,4))

example

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [21]:
example[[0,3],[1,2]]

array([ 2, 15])

In [23]:
row = [0,2,3,1]
col  =[3,0,2,1]

example[row,col]

array([ 4,  9, 15,  6])

In [24]:
import numpy as np

example = np.arange(1,17).reshape((4,4))

example

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [25]:
example[1,[1,3]]

array([6, 8])

In [26]:
example[[0,3],1]

array([ 2, 14])

In [27]:
example

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [28]:
example[0:,[1,2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [29]:
example[1:3,[1,2]]

array([[ 6,  7],
       [10, 11]])