In [1]:
import numpy as np

arr = np.arange(1,11)

arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [2]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [3]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [4]:
condition = arr <=4

arr[condition]

array([1, 2, 3, 4])

In [6]:
new_cond = (arr != 8) & (arr >=6)

arr[new_cond]

array([ 6,  7,  9, 10])

In [1]:
#-------------------------------ARITHEMATIC OPERATION-----------------------

import numpy as np

arr = np.arange(1,11)

In [2]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr-2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [4]:
arr*10

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [5]:
arr /10

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [6]:
((arr*10) +20 ) /5

array([ 6.,  8., 10., 12., 14., 16., 18., 20., 22., 24.])

In [7]:
arr * arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [8]:
arr / arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.subtract(arr,2)

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [10]:
np.multiply(arr,10)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [11]:
np.add(arr,20)

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [12]:
np.divide(arr,10)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [13]:
arr ** 3

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [14]:
np.power(arr,3)

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [15]:
np.sqrt(4)

2.0

In [16]:
arr % 5


array([1, 2, 3, 4, 0, 1, 2, 3, 4, 0], dtype=int32)

In [17]:
np.mod(arr, 5)

array([1, 2, 3, 4, 0, 1, 2, 3, 4, 0], dtype=int32)

In [18]:
np.sin(180)

-0.8011526357338304

In [19]:
np.cos(180)

-0.5984600690578581

In [20]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [21]:
np.log10(arr)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ])