In [1]:
import numpy as np

arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [2]:
np.sum(arr)

55

In [3]:
np.mean(arr)

5.5

In [4]:
np.median(arr)

5.5

In [5]:
np.min(arr)

1

In [6]:
np.max(arr)

10

In [7]:
np.std(arr)

2.8722813232690143

In [8]:
np.var(arr)

8.25

In [9]:
np.sqrt(np.var(arr))

2.8722813232690143

In [ ]:
#--------------solving second degree equation--------------------

import numpy as np

2X1 + X2 =5

-3X1 + 6X2 =0

In [10]:
coeff = np.array([[2,1], [-3,6]])

coeff

array([[ 2,  1],
       [-3,  6]])

In [11]:
output = np.array([5,0])

output

array([5, 0])

In [12]:
np.linalg.solve(coeff,output)

array([2., 1.])